### ISSUE TITLE
Slider not working

### ISSUE THREAD

**Issue by MisterChriz85** [nitsan-technologies/ns_all_sliders#1]
Hi, 

i use your typo3 slider (Royal Slider) since 4 days. 
Unfortunatly there is no "automatically" sliding of the pictures. It only works with click or keyboard nav buttons. I use version 8.7.4 on this site, i let the extension load the jqurey. I took the option "Auto Play" of course. 

Do you have any ideas, whats going wrong?

With best regards, 

Chris

**Comment by nitsan-technologies** [comment]
Dear Chris,

We have just resolved your mentioned issue, You can download latest extension at here https://github.com/nitsan-technologies/ns_all_sliders/archive/master.zip

Have a nice time :)
