### ISSUE TITLE
Allowed file extensions: SYS_FILE

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_all_sliders#12]
Hello,
i install your great plugin, but i have a problem with the gallery. 
When i want to create a new record can't taking a picture to the gallery. There is no allowed extensions.

Allowed file extensions:
SYS_FILE

Can you give me a note or a tip, please? Thanx a lot
Michael

**Comment by nataliamartinez** [comment]
I also have this same problem, have you found a solution? 
Let me know, thanks 
Natalia

**Comment by nitsan-technologies** [comment]
Hey Nataliamartinez,

Thanks for your message.

Problem:
Right, we have found that latest TYPO3 8.x get some TCA changes so that's it does not work. No problem, We will resolve it asap at here https://github.com/nitsan-t... You can keep watch & feel free to write any other issues or suggestions.

Quick Solution:
You can use our 2nd last version (1.0.0), It will work well. You can download it from here https://extensions.typo3.org/extension/ns_all_sliders/

Thank you very much for your time!
