### ISSUE TITLE
Any known problems if plugin is translated?

### ISSUE THREAD

**Issue by LimeUwe** [nitsan-technologies/ns_all_sliders#13]
Hi there,

I used the the Slider Plugin with the Slick-Slider option.
In default language all works well. Once the page and the plugin is translated (in my case to Hindi ;-) ), it stops loading the images in the front-end. No image resources are rendered in the frontend code.

Is this a known problem with multi-language setups?

Best regards
Uwe

**Comment by nitsan-technologies** [comment]
Hey @LimeUwe 

Thanks to using this extension.
And sorry for the delayed reply.

Hm, I have checked out this issue.
As per our understanding, you might have not translated records of storage page.
Something like this - https://i.imgur.com/TPPEB7V.png

Let us know if you are still facing this issue.

Cheers :)
