### ISSUE TITLE
No Information about removed Sliders - Breaking Systems

### ISSUE THREAD

**Issue by marxram** [nitsan-technologies/ns_all_sliders#14]
After updating to Version 4.0.0 I realized that most sliders (all except of owlcaroussel) have been removed. There was no comment on that anywhere. TER just knows "[FEATURE] Free version of this extension"

Nowhere is anything written about the dramatic feature change. Neither in TER or in the Extension Decomentation page, nor in Github. There is also nothing mentioned how to ge a non free version etc.

This is quite bad for everybody using more sliders.

Please inform anybody with the release information that the extension content has extremely changed!

**Comment by nitsan-technologies** [comment]
Hey @marxram 

Thanks for your feedback. We are extremely sorry for this inconvenient. We have updated press-release, Checkout https://github.com/nitsan-technologies/ns_all_sliders/releases/tag/4.0.0 (Of course, For your existing installation you can keep using FREE (without a license).

Cheers!
