### ISSUE TITLE
ns_slider on localhost 

### ISSUE THREAD

**Issue by Berlintypo3** [nitsan-technologies/ns_all_sliders#15]
I  testet ns_slider on a localhost Typo3 Version10.4.6 System in follow the steps to integrate in a content.
but there is not working. The firebug says some Errors in the javascripts. Nothing is loaded: in the sitecode are all images.
Have anybody experince?
``
Errors:
Uncaught TypeError: $ is undefined
<anonymous> http://localhost:8080/typo3/typo3conf/ext/ns_all_sliders/Resources/Public/slider/owl.carousel/owl-carousel/owl.carousel.js?1598858066:1718
<anonymous> http://localhost:8080/typo3/typo3conf/ext/ns_all_sliders/Resources/Public/slider/owl.carousel/owl-carousel/owl.carousel.js?1598858066:1755
+++	
Uncaught ReferenceError: jQuery is not defined
<anonymous> jQuery
+++	
Uncaught TypeError: $ is undefined
<anonymous> http://localhost:8080/typo3/typo3conf/ext/ns_all_sliders/Resources/Public/slider/owl.carousel/assets/js/owl.carousel2.thumbs.js?1598858066:216
<anonymous> http://localhost:8080/typo3/typo3conf/ext/ns_all_sliders/Resources/Public/slider/owl.carousel/assets/js/owl.carousel2.thumbs.js?1598858066:218
``

**Comment by nitsan-technologies** [comment]
Hi @Berlintypo3 

We have tested all the slider options in our local server and it is working fine.

For your site can you please make sure about the jquery comfliction? If on your site there any issue with the jquery then you need to fix it first and after that plugin work without any issue.

Thank you!
