### ISSUE TITLE
Many TCA migrations needed to perform for Typo3 9.5.X Ext ns_all_sliders (pro) 5.2.0

### ISSUE THREAD

**Issue by marxram** [nitsan-technologies/ns_all_sliders#16]
I am about to migrate to Typo3 9.5 LTS and found many TCA warnings. All related to the ns_all_slider extension.
I currently use the latest Version of ns_all_sliders (Pro) V 5.2.0
 
I am a pro customer and payed for ist, so it would be great, if it's state of the art compliant.

Here my results from Check TCA Migration in Typo3 9.5.22

### **TCA migrations need to be applied**
Check the following list and apply needed changes.

The TCA setting 'versioningWS' was set to a boolean value in TCA **tx_nsallsliders_domain_model_gallery**['ctrl']['versioningWS']
The TCA setting 'versioning_followPages' was removed as it is unused in TCA **tx_nsallsliders_domain_model_gallery**['ctrl']['versioning_followPages']
The TCA setting 'mergeIfNotBlank' was removed in TCA **tx_nsallsliders_domain_model_gallery**['columns']['starttime']['l10n_mode'] and changed to **tx_nsallsliders_domain_model_gallery**['columns']['starttime']['config']['behaviour']['allowLanguageSynchronization'] = true
The TCA setting 'mergeIfNotBlank' was removed in TCA **tx_nsallsliders_domain_model_gallery**['columns']['endtime']['l10n_mode'] and changed to **tx_nsallsliders_domain_model_gallery**['columns']['endtime']['config']['behaviour']['allowLanguageSynchronization'] = true
The TCA setting 'renderType' => 'inputDateTime' was added in TCA **tx_nsallsliders_domain_model_gallery**['columns']['starttime']['config']
The TCA setting 'renderType' => 'inputDateTime' was added in TCA **tx_nsallsliders_domain_model_gallery**['columns']['endtime']['config']
The config option 'max' has been removed from the TCA for renderType='inputDateTime' in **tx_nsallsliders_domain_model_gallery**['columns']['starttime']['config']['max']
The config option 'max' has been removed from the TCA for renderType='inputDateTime' in **tx_nsallsliders_domain_model_gallery**['columns']['endtime']['config']['max']
The 'foreign_types' property from TCA **tx_nsallsliders_domain_model_gallery**['columns']['image']['config'] and has been migrated to **tx_nsallsliders_domain_model_gallery**['columns']['image']['config']['overrideChildTca']['types']

**Comment by nitsan-technologies** [comment]
Dear @marxram 

Thanks for reporting us, we will work on this. You will get updates on your email (from T3Terminal platform) by tomorrow. I'm going to close this issue.

Cheers,
Sanjay
