### ISSUE TITLE
Owlslider random

### ISSUE THREAD

**Issue by herzogkienast** [nitsan-technologies/ns_all_sliders#17]
Hey guys,

I'm testing the owlslider and it works fine. Thank you. But: I need to show the pictures in random mode. Is this possible?

Best regards, 

Andrea

**Comment by nitsan-technologies** [comment]
Hello @herzogkienast 
Greetings of the day!

Thank you for the message. You meant You need the images in random order in the slider, So whenever the page is loaded/reloaded the image order should be changed, Something like this - http://www.landmarkmlp.com/js-plugin/owl.carousel/demos/randomOrder.html Right? 

If so, for now, it's not possible. If you are looking for this customization then, please contact us at here: https://t3terminal.com/typo3-customization-services

Thanks!
Team NITSAN
