### ISSUE TITLE
Images missing alt, link and crop fields

### ISSUE THREAD

**Issue by steffenk** [nitsan-technologies/ns_all_sliders#3]
I do not know why, as the TCA seems to be correct, but the fields from sys_file_reference are missing in BE
![bildschirmfoto 2017-10-17 um 11 23 05](https://user-images.githubusercontent.com/234874/31657550-f0a5315e-b32e-11e7-96e0-b07ed348eb51.png)

**Comment by steffenk** [comment]
found the issue in TCA-configuration.

instead of 
`foreign_types => array(...)`

it should be
`'overrideChildTca' => [
                            'types' => [...]
]`

**Comment by nitsan-technologies** [comment]
Hey @steffenk 

Thank you very much for your feedback. 👍 

**Resolved Problem:**
![resolved_problem](https://user-images.githubusercontent.com/2622317/32134591-8ab7ffec-bc0d-11e7-9de4-e2730444901b.png)

**Latest Extension:**
We have resolved & uploaded the latest version at https://extensions.typo3.org/extension/ns_all_sliders/ 

Please feel free to connect with us for any further help or support, Have a great time :)
