### ISSUE TITLE
[TASK] add lory slider

### ISSUE THREAD

**Issue by DanielRuf** [nitsan-technologies/ns_all_sliders#8]
https://github.com/meandmax/lory

It would be great to also have lory as slider solution.

**Comment by nitsan-technologies** [comment]
Dear @DanielRuf 

This feature is planned for upcoming major release, Thanks!

Cheers,
Sanjay

**Comment by DanielRuf** [comment]
I'm not sure if it makes sense to include more and more sliders ;-)

We use Swiper for all projects now.

https://github.com/nolimits4web/Swiper  
http://idangero.us/swiper/

**Comment by nitsan-technologies** [comment]
Hey @DanielRuf 

**Swiper Slider**
Aha, That sounds good, we will surely check in detail and try to include in this extension.

**Feedback**
Thanks for the feedback about more sliders. No worries, accordingly our experience, It's fine to integrate as much as 'POPULAR' plugins ;) You know, all-in-one solution. Feel free to let us know if you find any helpful sliders.

Cheers!
